name: cpjku_dcase23
channels:
  - defaults
dependencies:
  - pip=21.2.2
  - python=3.7.10
  - pip:
    - torch==1.11.0
    - torchaudio==0.11.0
    - torchinfo==1.7.0
    - torchvision==0.12.0
    - librosa==0.10.0.post2
    - pandas==1.3.5
    - scikit-learn==1.0.2
    - pytorch-lightning==1.9.4
    - wandb==0.15.4
    - timm==0.4.12

